"""Public aggregate-only GBM integration, figures, workbook, and final validation."""
from pathlib import Path
import json,hashlib,subprocess
import numpy as np,pandas as pd
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from matplotlib.colors import Normalize
from openpyxl import load_workbook
R=Path(__file__).resolve().parents[1];RUN='20260925T103000Z_discovery_v1';V2='20260925T144100Z_identity_resolution_v2';BASE=R/'results/GBM';O=BASE/'07_INTEGRATION'/'20260925T145000Z_integration_v1';O.mkdir(parents=True,exist_ok=False);F=O/'figures';F.mkdir()
def load(stage,fn,run=RUN):return pd.read_csv(BASE/stage/run/fn,sep='\t')
def save(d,p):d.to_csv(p,sep='\t',index=False,na_rep='NA')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
e=load('02_MAPPING','direct_relations.tsv');met=load('01_CAMP','metabolite_unpaired_all.tsv');assoc=load('03_PATIENT','tumor_association_all_families.tsv');rna=load('03_PATIENT','RNA_unpaired_all_families.tsv',V2);sc=load('06_EXTERNAL','sc_cross_study.tsv');rank=load('06_EXTERNAL','sc_source_stability.tsv');prof=load('06_EXTERNAL','sc_celltype_profiles.tsv');coverage=load('02_MAPPING','mapping_coverage.tsv');genes=load('02_MAPPING','genes_unique.tsv')
assert e.relation_id.is_unique and genes.gene.is_unique and met.feature_id.is_unique
rels=e.copy();cols=['feature_id','n','n_reference','effect','p_value','q_value','original_cohort_q'];rels=rels.merge(met[cols].rename(columns={c:'metabolite_'+c for c in cols if c!='feature_id'}),on='feature_id',validate='many_to_one')
for fam,prefix in [('REL_TUMOR_PRIMARY','patient_primary'),('REL_TUMOR_AVAILABLE','patient_available'),('REL_TUMOR_PATH_PASS','patient_path_pass'),('REL_TUMOR_AGE_SEX','patient_age_sex')]:
 d=assoc[assoc.test_family.eq(fam)];cols=['relation_id','n','effect','ci_lower','ci_upper','p_value','q_value','status','reason'];rels=rels.merge(d[cols].rename(columns={c:prefix+'_'+c for c in cols if c!='relation_id'}),on='relation_id',validate='one_to_one')
gtab=genes.copy()
for fam,prefix in [('RNA_UNPAIRED_CURRENT','RNA'),('RNA_UNPAIRED_AGE_SEX','RNA_age_sex')]:
 d=rna[rna.test_family.eq(fam)];cols=['gene','n','n_reference','effect','ci_lower','ci_upper','p_value','q_value','status','reason'];gtab=gtab.merge(d[cols].rename(columns={c:prefix+'_'+c for c in cols if c!='gene'}),on='gene',validate='one_to_one')
gtab=gtab.merge(sc.drop(columns='stable_gene_id'),on='gene',validate='one_to_one');gtab['relation_ids']=gtab.gene.map(e.groupby('gene').relation_id.agg(';'.join));gtab['n_relations']=gtab.gene.map(e.groupby('gene').size());gtab['n_nominal_patient_relations']=gtab.gene.map(rels[rels.patient_primary_p_value.lt(.05)].groupby('gene').size()).fillna(0).astype(int)
gtab['RNA_background']=np.select([gtab.RNA_p_value.isna(),gtab.RNA_q_value.lt(.05),gtab.RNA_p_value.lt(.05)],['NOT_EVALUABLE','FDR_SUPPORTED_EXPLORATORY_TPM','NOMINAL_EXPLORATORY'],default='NOT_SUPPORTED_THIS_TEST')
gtab['functional_evidence']='NOT_RUN';gtab['external_metabolite_validation']='NOT_RUN';gtab['data_limitations']='6 unmatched GTEx references;cohort confounding;current biochemical catalog incomplete;sc source descriptive only';gtab['current_pool']=True;gtab['next_action']='retain full candidate;do not infer function from expression'
rels=rels.merge(gtab.drop(columns=['stable_gene_id','relation_ids','n_relations','n_nominal_patient_relations']),on='gene',validate='many_to_one',suffixes=('','_cell_source'));assert len(rels)==len(e)==171 and len(gtab)==142
rels['discovery_gate_original']=rels.discovery_gate;rels['discovery_gate']='MASTER_TN_CORROBORATED_BY_PINNED_CPTAC_LOADER_V2';rels['normal_identity_audit_path']=str((BASE/'01_CAMP'/V2).relative_to(R));rels['patient_evidence']=np.select([rels.patient_primary_p_value.isna(),rels.patient_primary_q_value.lt(.05),rels.patient_primary_p_value.lt(.05)],['NOT_EVALUABLE','FDR_SUPPORTED','NOMINAL_EXPLORATORY'],default='NOT_SUPPORTED_THIS_TEST');rels['metabolite_evidence']=np.where(rels.metabolite_q_value.lt(.05),'FDR_SUPPORTED_UNPAIRED','NOMINAL_EXPLORATORY_UNPAIRED')
metcurrent=met.copy();metcurrent['historical_status']=metcurrent.status;metcurrent['current_status']=np.where(metcurrent.p_value.notna(),'DONE','NOT_EVALUABLE');metcurrent['current_reason']=np.where(metcurrent.p_value.notna(),'master_TN_corroborated_in_identity_v2;unpaired_reference_confounding_remains',metcurrent.reason)
save(rels,O/'candidate_relations_integrated.tsv');save(gtab,O/'candidate_genes_integrated.tsv');save(metcurrent,O/'all_metabolites_current_view.tsv');save(coverage,O/'mapping_coverage_current.tsv')
# Full-candidate point plots: no significance selection, gray NA, common color/detection scale.
ordered=sorted(genes.gene);studies=['Darmanis2017','Neftel2019'];types=['Neoplastic','Myeloid','Lymphoid','OPC','Oligodendrocyte','Astrocyte','Neuron','Vascular','Other glial'];vmax=float(prof.effect.max());cmap=plt.get_cmap('viridis');norm=Normalize(0,vmax)
plt.rcParams.update({'font.family':'DejaVu Sans','font.size':9,'pdf.fonttype':42,'ps.fonttype':42})
with PdfPages(F/'GBM_all142_cell_source_dotplots.pdf') as pdf:
 for page,start in enumerate(range(0,len(ordered),48),1):
  gg=ordered[start:start+48];fig,axes=plt.subplots(1,2,figsize=(15,16),sharey=True)
  for ax,study in zip(axes,studies):
   df=prof[prof.cohort.eq(study)].set_index(['gene','celltype'])
   for yi,g in enumerate(gg):
    for xi,t in enumerate(types):
     if (g,t) in df.index:
      q=df.loc[(g,t)]
      if q.status=='DONE':ax.scatter(xi,yi,s=8+130*q.mean_detection_fraction,c=[cmap(norm(q.effect))],edgecolors='none');continue
     ax.scatter(xi,yi,s=12,c='#d9d9d9',marker='x',linewidths=.7)
   ax.set_xticks(range(len(types)),types,rotation=60,ha='right');ax.set_yticks(range(len(gg)),gg);ax.set_ylim(len(gg)-.5,-.5);ax.set_xlim(-.7,len(types)-.3);ax.set_title(study+' | donor-equal');ax.grid(axis='y',alpha=.13);ax.set_axisbelow(True);ax.spines[['top','right']].set_visible(False)
  fig.suptitle(f'GBM candidate cell expression sources | all142 | page {page}\nColor: donor-equal mean log1p(CP10k); size: detection; gray x: not evaluable',fontsize=13);fig.subplots_adjust(left=.12,right=.90,bottom=.12,top=.93,wspace=.12);cax=fig.add_axes([.92,.30,.015,.35]);fig.colorbar(plt.cm.ScalarMappable(norm=norm,cmap=cmap),cax=cax,label='Mean log1p(CP10k)');pdf.savefig(fig);fig.savefig(F/f'GBM_cell_sources_page{page}.png',dpi=170);plt.close(fig)
# All142 heatmap; raw donor means kept, no per-gene z score.
heat=prof.pivot(index='gene',columns=['cohort','celltype'],values='effect').reindex(ordered);fig,ax=plt.subplots(figsize=(13,32));cm=plt.get_cmap('viridis').copy();cm.set_bad('#e7e7e7');im=ax.imshow(heat.to_numpy(float),aspect='auto',cmap=cm,vmin=0,vmax=vmax,interpolation='nearest');ax.set_yticks(range(len(ordered)),ordered,fontsize=7);ax.set_xticks(range(len(heat.columns)),[s.replace('2017','17').replace('2019','19')+' / '+t for s,t in heat.columns],rotation=90,fontsize=8);ax.set_title('GBM all142 | donor-equal expression; gray = not evaluable');fig.colorbar(im,ax=ax,fraction=.025,pad=.025,label='Mean log1p(CP10k)');fig.tight_layout();fig.savefig(F/'GBM_all142_cell_source_heatmap.pdf');fig.savefig(F/'GBM_all142_cell_source_heatmap.png',dpi=130);plt.close(fig)
# Nominal correlation view explicitly carries all FDR results.
nom=rels[rels.patient_primary_p_value.lt(.05)].sort_values('patient_primary_p_value');fig,ax=plt.subplots(figsize=(9,7));yy=np.arange(len(nom));x=nom.patient_primary_effect.to_numpy();err=np.vstack([x-nom.patient_primary_ci_lower,nom.patient_primary_ci_upper-x]);ax.errorbar(x,yy,xerr=err,fmt='o',color='#21618c',capsize=3);ax.axvline(0,c='#888',ls='--',lw=.8);ax.set_yticks(yy,[f'{g} | {m}' for g,m in zip(nom.gene,nom.metabolite_name)]);ax.invert_yaxis();ax.set_xlabel('Spearman rho, pointwise bootstrap 95% CI');ax.set_title('GBM tumor associations | 14 nominal P<0.05; none FDR<0.05');fig.tight_layout();fig.savefig(F/'GBM_nominal_associations.png',dpi=180);fig.savefig(F/'GBM_nominal_associations.pdf');plt.close(fig)
notes=pd.DataFrame([('范围','713特征清单；697可比较；480名义工作特征；23已映射特征；171关系；142基因'),('设计','74肿瘤对6非配对GTEx正常；并非BRCA式配对'),('身份','6正常在processed sampleanno的标签冲突由CPTAC v0.9.7明确组织规则与MasterMapping一致解决，旧结果不覆盖'),('RNA','log2(TPM+1)非配对Welch探索背景；RNA均值差不是精确倍数；年龄/性别HC3敏感性'),('关联','肿瘤内Spearman、9999置换、4000bootstrap；原值/可用值/病理PASS/年龄性别四族独立BH'),('单细胞','Darmanis4来源与Neftel23来源标签，GBmap仅取Neftel，原Darmanis排除；全142基因；不做机制推断'),('缺项','457特征待补精确生化映射，其中423为脂质；3个RNA名称未匹配；不填假阴性'),('解读','RNA q显著不等于代谢物—RNA关联成立；14条名义相关均未过FDR'),('来源','逐患者/逐细胞数据只在server165；本表为公开汇总')],columns=['项目','说明'])
with pd.ExcelWriter(O/'GBM_全候选分析_142基因171关系.xlsx',engine='openpyxl') as wr:
 for name,d in [('阅读说明',notes),('全部171关系',rels),('全部142基因',gtab),('名义关联14条',nom),('代谢物713全表',metcurrent),('480特征映射覆盖',coverage),('RNA全部检验族',rna),('关联全部检验族',assoc),('单细胞来源',rank),('两研究比较',sc),('细胞类别长表',prof)]:d.to_excel(wr,sheet_name=name,index=False)
wb=load_workbook(O/'GBM_全候选分析_142基因171关系.xlsx')
from openpyxl.styles import Font,PatternFill,Alignment
for ws in wb:
 ws.freeze_panes='A2';ws.auto_filter.ref=ws.dimensions
 for cell in ws[1]:cell.fill=PatternFill('solid',fgColor='17365D');cell.font=Font(color='FFFFFF',bold=True)
 for col in ws.columns:ws.column_dimensions[col[0].column_letter].width=min(45,max(14,len(str(col[0].value))+2))
 if ws.title=='阅读说明':ws.column_dimensions['B'].width=115
wb.save(O/'GBM_全候选分析_142基因171关系.xlsx');assert wb['全部171关系'].max_row==172 and wb['全部142基因'].max_row==143
summary=dict(status='PARTIAL',completed_scope='current reviewed mapping cohort analysis and two-study cell-source mainline',all_features=713,evaluable_metabolites=697,metabolites_p005=480,metabolites_current_q005=int(met.q_value.lt(.05).sum()),mapped_features=23,mapping_pending=457,direct_relations=171,genes=142,evaluable_patient_relations=168,patient_P005=14,patient_q005=0,RNA_evaluable=139,RNA_P005=85,RNA_q005=75,sc_top_all_agreement=int(sc.same_top_all_categories.eq(True).sum()),sc_top_all_evaluable=int(sc.same_top_all_categories.notna().sum()),sc_top_shared_agreement=int(sc.same_top_shared_categories.eq(True).sum()),sc_top_shared_evaluable=int(sc.same_top_shared_categories.notna().sum()),source_identity_conflict='resolved_in_v2',functional_work='NOT_RUN_not_required_by_mainline',original_statistics_modified=False)
(O/'validation.json').write_text(json.dumps(summary,indent=2));(O/'analysis_spec.json').write_text(json.dumps(dict(version='gbm_integration_v1',joins='exact feature_id+stable_gene_id;RNA/cell source gene one-to-one;no best P selection',code_commit=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip(),new_statistics=False,figures='all142 cell-source dotplots and heatmap;nominal14 association view explicitly not FDR',public_run_label_note='server computation root retains discovery run ID;identity v2 delivery directory identifies revision batch'),indent=2))
readme=f'''# GBM首轮分析交付\n\n## 本轮问题\n沿用BRCA的发现→直接映射→肿瘤内关联/RNA背景→全候选单细胞来源→整合主线。\n\n## 输入与范围\n74个肿瘤和6个非配对正常作者病例。原CAMP统计保留。正常来自GTEx，不做伪配对。713个输入特征均有记录；697个可比较，P<0.05工作池480个。\n\n## 实际结果\n- 当前完整代谢特征族q<0.05：{summary['metabolites_current_q005']}；与冻结的589化学键癌种表分开。\n- 已复用审定证据映射23特征、171直接关系、142基因。457特征待补映射，其中423为脂质；本轮不是穷尽数据库映射。\n- 肿瘤内168关系可评估，14条P<0.05，0条q<0.05。最小P关系SHMT1—serine：rho=-0.3952，P=0.0006，q=0.1008。\n- RNA 139基因可评估，85个P<0.05、75个q<0.05；G6PC1、GBA1、SLC60A2没有精确名称匹配，保留不可评估。\n- 单细胞Darmanis2017：3589细胞、4供者标签、测到140候选；Neftel2019（GBmap再注释）：19030细胞、23供者标签、测到137候选。\n- 两研究各自全类别最高来源一致{summary['sc_top_all_agreement']}/{summary['sc_top_all_evaluable']}；仅共同可评估的Myeloid/Neoplastic两类比较为{summary['sc_top_shared_agreement']}/{summary['sc_top_shared_evaluable']}。后者类别更少，不能据此夸大跨研究一致性。\n\n## 新手解释\nRNA在肿瘤和正常之间不同，不代表它与对应代谢物在肿瘤内部显著相关。当前GBM没有代谢物—RNA关系通过FDR，14条只能作为探索线索。所有142基因保留，不按关联显著性筛掉。单细胞回答表达在哪里，不证明代谢物来源、酶活或功能。\n\n## 限制/反证\n6个正常样本的processed sampleanno标签与主映射冲突，已由固定版本CPTAC读取包明确组织定义佐证主映射；原文件不改、旧冲突审计保留。样本不是肿瘤—癌旁配对，GTEx来源混杂仍在；RNA用log2(TPM+1)Welch及年龄性别HC3，是探索性连续表达背景，不是原始counts差异模型。缺失掩码仅称作者可用值。功能与外部代谢复现未开展；单细胞跨研究患者别名未独立核实。\n\n## 当前决定\n交付当前已映射范围的完整结果。保留全480工作特征及457待映射清单，不把未映射当无生物学关系。14条相关均不升级为FDR支持机制。\n\n## 下一步\n优先补齐未映射明确小分子与脂质精确底物证据；经稳定ID核实3个RNA旧名后另建版本。新增关系必须对新全族重新BH，不能照抄本版q。\n\n## 复现\n服务器路径：/public3/xuzx/Cancer/pancancer_metabolomics_direct_matrix_20260716/results/collaborative/GBM/A/{RUN}/。按code中的gbm_discovery_v1.py、gbm_mapping_v1.py、gbm_patient_v1.py、gbm_identity_RNA_v2.py、gbm_extract_sc_v1.py、gbm_sc_source_v1.py、gbm_integrate_v1.py顺序；新目录、独占锁、输入SHA与各阶段参数见source_manifest/analysis_spec。无原始质谱下载，患者级矩阵与单细胞明细只留server165。\n\n## 文件\n- GBM_全候选分析_142基因171关系.xlsx：导师讨论用完整工作簿。\n- candidate_relations_integrated.tsv、candidate_genes_integrated.tsv：关系级和基因级完整表。\n- figures/：全142基因点图（3页）与热图；14名义关系的CI图。\n'''
(O/'README_CN.md').write_text(readme,encoding='utf-8');(R/'docs/GBM_CURRENT_RESULTS_CN.md').write_text(readme+'\n当前交付目录：'+str(O.relative_to(R))+'\n',encoding='utf-8')
paths=[p for p in BASE.rglob('*.tsv') if '07_INTEGRATION' not in p.parts]+[Path(__file__)];save(pd.DataFrame([dict(source_id=p.name,path_or_url=str(p.relative_to(R)),sha256=sha(p)) for p in paths]),O/'source_manifest.tsv');save(pd.DataFrame([dict(file=str(p.relative_to(O)),sha256=sha(p)) for p in O.rglob('*') if p.is_file()]),O/'checksums.tsv')
# Complete seven-stage index with explicit outstanding scope.
index=[]
for stage,run,status,scope,code,reason in [('01_CAMP',RUN,'DONE','full feature discovery;normal conflict superseded by identity v2','gbm_discovery_v1.py','unpaired_source_confounding_remains'),('01_CAMP',V2,'DONE','independent explicit tissue assignment corroboration','gbm_identity_RNA_v2.py','processed_sampleanno_conflict_resolved_without_source_changes'),('02_MAPPING',RUN,'PARTIAL','171 reviewed direct relations;142 genes','gbm_mapping_v1.py','457_work_features_pending_precise_mapping'),('03_PATIENT',RUN,'DONE','168 of171 evaluable tumor relations;four families','gbm_patient_v1.py','3_exact_gene_symbols_not_found;RNA status superseded by v2'),('03_PATIENT',V2,'DONE','139 of142 evaluable unpaired RNA;two families','gbm_identity_RNA_v2.py','3_exact_symbols_not_found;no_paired_design'),('04_ROBUSTNESS',RUN,'DONE','available-value metabolite sensitivity;association_QC_and_covariates_indexed_in03','gbm_discovery_v1.py','original_normal_conflict_interpretation_superseded_by01v2'),('05_FUNCTION',RUN,'NOT_RUN','function interventions not part of current mainline','','no_functional_proof_claimed'),('06_EXTERNAL',RUN,'DONE','all142 genes across2 sc source studies','gbm_sc_source_v1.py','expression_source_only;not_external_metabolite_validation'),('07_INTEGRATION',O.name,'PARTIAL','current scoped full relation/gene integration','gbm_integrate_v1.py','mapping_remaining457;other_missing_rows_retained')]:
 index.append(dict(cancer='GBM',stage_id=stage,run_id=run,analysis_version='gbm_current_mainline_v1',status=status,scope=scope,result_path=f'results/GBM/{stage}/{run}' if stage!='05_FUNCTION' else 'docs/GBM_CURRENT_RESULTS_CN.md',code_path='code/'+code if code else 'NA',git_branch='analysis/gbm-discovery-20260925',reason=reason,next_action='see_current_GBM_report'))
save(pd.DataFrame(index),R/'coordination/stages/GBM.tsv');print(json.dumps(summary));print(str(O))
